basePath: /
definitions:
  handler.errorResponse:
    properties:
      error:
        type: string
    type: object
  model.CreateSubscriptionRequest:
    properties:
      end_date:
        type: string
        x-order: "5"
      price:
        minimum: 0
        type: integer
        x-order: "2"
      service_name:
        minLength: 2
        type: string
        x-order: "1"
      start_date:
        type: string
        x-order: "4"
      user_id:
        type: string
        x-order: "3"
    required:
    - price
    - service_name
    - start_date
    - user_id
    type: object
  model.SubscriptionResponse:
    properties:
      end_date:
        type: string
        x-order: "6"
      id:
        type: string
        x-order: "1"
      price:
        type: integer
        x-order: "3"
      service_name:
        type: string
        x-order: "2"
      start_date:
        type: string
        x-order: "5"
      user_id:
        type: string
        x-order: "4"
    type: object
host: localhost:8090
info:
  contact:
    email: gsrnode@gmail.com
    name: API Support
    url: https://github.com/gsrlabs/subscriptions-service
  description: API Server for Subscription Management.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Subscription Service API
  version: "1.0"
paths:
  /subscriptions:
    get:
      description: List subscriptions with optional filters
      parameters:
      - description: User ID
        format: uuid
        in: query
        name: user_id
        type: string
      - description: Service name
        in: query
        name: service_name
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SubscriptionResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: List subscriptions
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Create a new subscription
      parameters:
      - description: Subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.CreateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Create subscription
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Delete subscription by ID
      parameters:
      - description: Subscription ID
        example: '"550e8400-e29b-41d4-a716-446655440000"'
        format: uuid
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Delete subscription
      tags:
      - subscriptions
    get:
      description: Get subscription by ID
      parameters:
      - description: Subscription ID
        example: '"550e8400-e29b-41d4-a716-446655440000"'
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get subscription
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Update subscription by ID
      parameters:
      - description: Subscription ID
        example: '"550e8400-e29b-41d4-a716-446655440000"'
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: Updated subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.CreateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Update subscription
      tags:
      - subscriptions
  /subscriptions/summary:
    get:
      description: Calculate total cost of subscriptions for a period
      parameters:
      - description: Start period
        example: '"01-2025"'
        in: query
        name: from
        required: true
        type: string
      - description: End period
        example: '"12-2025"'
        in: query
        name: to
        required: true
        type: string
      - description: User ID
        format: uuid
        in: query
        name: user_id
        type: string
      - description: Service name
        example: '"Netflix"'
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Example: {"total": 1500}'
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Aggregate subscriptions cost
      tags:
      - subscriptions
swagger: "2.0"
